/** dsh-memory — SQLite schema (DDL + idempotent migration + FTS rebuild). */
import type { DatabaseSync } from 'node:sqlite';
export declare const DDL = "\nCREATE TABLE IF NOT EXISTS memories (\n  id            TEXT PRIMARY KEY,\n  layer         TEXT NOT NULL,\n  kind          TEXT NOT NULL,\n  tier          INTEGER NOT NULL,\n  topic         TEXT NOT NULL,\n  content       TEXT NOT NULL,\n  importance    INTEGER NOT NULL,\n  quality       INTEGER NOT NULL,\n  epistemic     TEXT NOT NULL,\n  heat          REAL NOT NULL,\n  created       INTEGER NOT NULL,\n  updated       INTEGER NOT NULL,\n  last_accessed INTEGER NOT NULL,\n  archived      INTEGER NOT NULL DEFAULT 0,\n  low_quality   INTEGER NOT NULL DEFAULT 0,\n  window_freq   INTEGER NOT NULL DEFAULT 0,\n  window_start  INTEGER,\n  archived_at   INTEGER,\n  session_id    TEXT\n);\nCREATE INDEX IF NOT EXISTS idx_mem_tier   ON memories(tier, archived);\nCREATE INDEX IF NOT EXISTS idx_mem_layer  ON memories(layer, tier);\nCREATE INDEX IF NOT EXISTS idx_mem_access ON memories(last_accessed);\nCREATE VIRTUAL TABLE IF NOT EXISTS mem_fts USING fts5(content, topic);\n\nCREATE TABLE IF NOT EXISTS episodes (\n  id          TEXT PRIMARY KEY,\n  session_id  TEXT NOT NULL,\n  ts          INTEGER NOT NULL,\n  summary     TEXT NOT NULL,\n  tools_used  TEXT,\n  topic       TEXT NOT NULL DEFAULT 'general',\n  extracted   INTEGER NOT NULL DEFAULT 0,\n  archived    INTEGER NOT NULL DEFAULT 0,\n  archived_at INTEGER,\n  created     INTEGER NOT NULL\n);\nCREATE INDEX IF NOT EXISTS idx_episodes_session ON episodes(session_id, ts);\nCREATE INDEX IF NOT EXISTS idx_episodes_arch    ON episodes(archived, ts);\nCREATE VIRTUAL TABLE IF NOT EXISTS ep_fts USING fts5(summary, topic);\n\nCREATE TABLE IF NOT EXISTS failure_memories (\n  id           INTEGER PRIMARY KEY AUTOINCREMENT,\n  memory_id    TEXT NOT NULL,\n  old_content  TEXT,\n  new_content  TEXT,\n  corrected_at INTEGER NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS forget_runs (\n  id            INTEGER PRIMARY KEY AUTOINCREMENT,\n  ts            INTEGER NOT NULL,\n  candidate_sha TEXT,\n  decisions     TEXT,\n  applied       INTEGER NOT NULL DEFAULT 0,\n  status        TEXT NOT NULL\n);\n";
/**
 * Idempotent column migration: PRAGMA table_info probe + ADD COLUMN, swallowing
 * the concurrent duplicate-column error (mneme v0.4.7 lesson — schema evolution
 * must be idempotent). v3.0.0 ships a full DDL, so this is the extension point
 * for future v3.x columns.
 */
export declare function migrateColumns(db: DatabaseSync): void;
/** Rebuild the FTS index from the content table (boot-time alignment). */
export declare function rebuildFts(db: DatabaseSync): void;
